name: appscom
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  rive: ^0.13.17
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  flutter_svg: ^2.0.10+1
  google_fonts: ^6.2.1
  get_it: ^7.7.0
  table_calendar: ^3.0.6
  http: ^1.2.2
  go_router: ^14.2.0
  intl: ^0.19.0
  flutter_staggered_grid_view: ^0.7.0
  device_preview: ^1.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner:
  flutter_gen_runner:
  flutter_launcher_icons: ^0.13.1
  mockito: ^5.4.4

flutter_icons:
  android:
    generate: true
    image_path: "assets/logo/logo.png"
    min_sdk_android: 21
  ios:
    generate: true
    image_path: "assets/logo/logo.png"
  web:
    generate: true
    image_path: "path/to/image.png"
  windows:
    generate: true
    image_path: "assets/logo/logo.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/logo/logo.png"

flutter_gen:
  output: lib/gen/
  line_length: 80

  integrations:
    flutter_svg: true

  colors:
    inputs:
      - assets/color/colors.xml

# For information on the generic Dart part of this file, see the
flutter:
  uses-material-design: true
  assets:
    - assets/logo/
    - assets/rive/
    - assets/icons/
    # otras rutas de assets...


    # PNGs
    - assets/png/
    - assets/png/m8/
    - assets/png/m13/
    - assets/png/m10/
    - assets/png/m19/
    - assets/png/m26/
    - assets/png/m27/
    - assets/png/m28/
    - assets/png/m29/
    - assets/png/m31/
    - assets/png/m35/
    - assets/png/m37/
    - assets/png/m40/
    - assets/png/m43/
    - assets/png/m45/
    - assets/png/m50/
    - assets/png/m52/
    - assets/png/m53/
    - assets/png/m57/
    - assets/png/m64/
    - assets/png/m89/
    - assets/png/m99/
    - assets/png/m98/
    - assets/png/m100/
    - assets/png/m97/
    - assets/png/m96/
    - assets/png/m95/

    # SVGs
    - assets/svg/
    - assets/svg/m3/
    - assets/svg/m4/
    - assets/svg/m6/
    - assets/svg/m7/
    - assets/svg/m8/
    - assets/svg/m9/
    - assets/svg/m11/
    - assets/svg/m12/
    - assets/svg/m14/
    - assets/svg/m18/
    - assets/svg/m19/
    - assets/svg/m21/
    - assets/svg/m22/
    - assets/svg/m32/
    - assets/png/m45/
    - assets/svg/m51/
    - assets/png/m52/
    - assets/png/m30/
    - assets/svg/m52/
    - assets/svg/m53/
    - assets/svg/m76/
    - assets/png/m175/
    - assets/svg/m175/

    # Colors
    - assets/color/

    # google fonts for testing
    - google_fonts/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Abolition
      fonts:
        - asset: assets/fonts/Abolition-Regular.ttf

    - family: Proxima Nova
      fonts:
        - asset: assets/fonts/Proxima-Nova.otf

    - family: Intel
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
          weight: 600
    
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700

  # To add assets to your application, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
